// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

let flag = 2;
let sum = 2;
let breakPoint = 4000000;
let initialTerms = [1, 2];

function fibo(arr) {
  let result = arr
  last = arr[arr.length - 1];
  lastButOne = arr[arr.length - 2];

  result.push(last + lastButOne);

  return result;
}

while (flag < breakPoint) {
  let res = fibo(initialTerms)
  let endIdx = res[res.length - 1]
  flag = endIdx;
  
  if(endIdx%2 === 0){
    sum = sum += endIdx;
  }
}
